{
 "title": "lab DataNetworks - Valentin Sandoz",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Puissances mesurée",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"SIn09\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"power\")\n  |> aggregateWindow(every: duration(v:int(v:v.windowPeriod)*10), fn: mean, createEmpty: true)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Températures",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"SIn09\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature\")\n  |> aggregateWindow(every: duration(v:int(v:v.windowPeriod)*10), fn: mean, createEmpty: true)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Puissances totale",
   "type": "timeseries",
   "description": "Puissance totale mesurée par toutes les smart plugs branchées",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"SIn09\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"power\")\n  |> aggregateWindow(every: duration(v:int(v:v.windowPeriod)*10), fn: mean, createEmpty: true)\n  |> group(columns:[\"_time\"], mode:\"by\")\n  |> sum(column:\"_value\")\n  |> group()\n  |> yield(name: \"mean\")\n"
    }
   ]
  },
  { "type": "cloudspout-button-panel", "gridPos": { "h": 2, "w": 6, "x": 0, "y": 18 } },
  { "type": "cloudspout-button-panel", "gridPos": { "h": 2, "w": 6, "x": 6, "y": 18 } }
 ]
}